# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/deli/Dokumenty/Studia/PO II Semestr/zad2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/deli/Dokumenty/Studia/PO II Semestr/zad2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/deli/Dokumenty/Studia/PO II Semestr/zad2/CMakeFiles" "/home/deli/Dokumenty/Studia/PO II Semestr/zad2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/deli/Dokumenty/Studia/PO II Semestr/zad2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ComplexQuiz-ut

# Build rule for target.
ComplexQuiz-ut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ComplexQuiz-ut
.PHONY : ComplexQuiz-ut

# fast build rule for target.
ComplexQuiz-ut/fast:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/build
.PHONY : ComplexQuiz-ut/fast

#=============================================================================
# Target rules for targets named ComplexQuiz

# Build rule for target.
ComplexQuiz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ComplexQuiz
.PHONY : ComplexQuiz

# fast build rule for target.
ComplexQuiz/fast:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/build
.PHONY : ComplexQuiz/fast

#=============================================================================
# Target rules for targets named STAT

# Build rule for target.
STAT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STAT
.PHONY : STAT

# fast build rule for target.
STAT/fast:
	$(MAKE) -f CMakeFiles/STAT.dir/build.make CMakeFiles/STAT.dir/build
.PHONY : STAT/fast

#=============================================================================
# Target rules for targets named doctest

# Build rule for target.
doctest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doctest
.PHONY : doctest

# fast build rule for target.
doctest/fast:
	$(MAKE) -f CMakeFiles/doctest.dir/build.make CMakeFiles/doctest.dir/build
.PHONY : doctest/fast

#=============================================================================
# Target rules for targets named QUIZ

# Build rule for target.
QUIZ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QUIZ
.PHONY : QUIZ

# fast build rule for target.
QUIZ/fast:
	$(MAKE) -f CMakeFiles/QUIZ.dir/build.make CMakeFiles/QUIZ.dir/build
.PHONY : QUIZ/fast

#=============================================================================
# Target rules for targets named EXPR

# Build rule for target.
EXPR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EXPR
.PHONY : EXPR

# fast build rule for target.
EXPR/fast:
	$(MAKE) -f CMakeFiles/EXPR.dir/build.make CMakeFiles/EXPR.dir/build
.PHONY : EXPR/fast

#=============================================================================
# Target rules for targets named COMP

# Build rule for target.
COMP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 COMP
.PHONY : COMP

# fast build rule for target.
COMP/fast:
	$(MAKE) -f CMakeFiles/COMP.dir/build.make CMakeFiles/COMP.dir/build
.PHONY : COMP/fast

src/Complex.o: src/Complex.cpp.o

.PHONY : src/Complex.o

# target to build an object file
src/Complex.cpp.o:
	$(MAKE) -f CMakeFiles/COMP.dir/build.make CMakeFiles/COMP.dir/src/Complex.cpp.o
.PHONY : src/Complex.cpp.o

src/Complex.i: src/Complex.cpp.i

.PHONY : src/Complex.i

# target to preprocess a source file
src/Complex.cpp.i:
	$(MAKE) -f CMakeFiles/COMP.dir/build.make CMakeFiles/COMP.dir/src/Complex.cpp.i
.PHONY : src/Complex.cpp.i

src/Complex.s: src/Complex.cpp.s

.PHONY : src/Complex.s

# target to generate assembly for a file
src/Complex.cpp.s:
	$(MAKE) -f CMakeFiles/COMP.dir/build.make CMakeFiles/COMP.dir/src/Complex.cpp.s
.PHONY : src/Complex.cpp.s

src/Expression.o: src/Expression.cpp.o

.PHONY : src/Expression.o

# target to build an object file
src/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/EXPR.dir/build.make CMakeFiles/EXPR.dir/src/Expression.cpp.o
.PHONY : src/Expression.cpp.o

src/Expression.i: src/Expression.cpp.i

.PHONY : src/Expression.i

# target to preprocess a source file
src/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/EXPR.dir/build.make CMakeFiles/EXPR.dir/src/Expression.cpp.i
.PHONY : src/Expression.cpp.i

src/Expression.s: src/Expression.cpp.s

.PHONY : src/Expression.s

# target to generate assembly for a file
src/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/EXPR.dir/build.make CMakeFiles/EXPR.dir/src/Expression.cpp.s
.PHONY : src/Expression.cpp.s

src/Quiz.o: src/Quiz.cpp.o

.PHONY : src/Quiz.o

# target to build an object file
src/Quiz.cpp.o:
	$(MAKE) -f CMakeFiles/QUIZ.dir/build.make CMakeFiles/QUIZ.dir/src/Quiz.cpp.o
.PHONY : src/Quiz.cpp.o

src/Quiz.i: src/Quiz.cpp.i

.PHONY : src/Quiz.i

# target to preprocess a source file
src/Quiz.cpp.i:
	$(MAKE) -f CMakeFiles/QUIZ.dir/build.make CMakeFiles/QUIZ.dir/src/Quiz.cpp.i
.PHONY : src/Quiz.cpp.i

src/Quiz.s: src/Quiz.cpp.s

.PHONY : src/Quiz.s

# target to generate assembly for a file
src/Quiz.cpp.s:
	$(MAKE) -f CMakeFiles/QUIZ.dir/build.make CMakeFiles/QUIZ.dir/src/Quiz.cpp.s
.PHONY : src/Quiz.cpp.s

src/Statistics.o: src/Statistics.cpp.o

.PHONY : src/Statistics.o

# target to build an object file
src/Statistics.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/Statistics.cpp.o
	$(MAKE) -f CMakeFiles/STAT.dir/build.make CMakeFiles/STAT.dir/src/Statistics.cpp.o
.PHONY : src/Statistics.cpp.o

src/Statistics.i: src/Statistics.cpp.i

.PHONY : src/Statistics.i

# target to preprocess a source file
src/Statistics.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/Statistics.cpp.i
	$(MAKE) -f CMakeFiles/STAT.dir/build.make CMakeFiles/STAT.dir/src/Statistics.cpp.i
.PHONY : src/Statistics.cpp.i

src/Statistics.s: src/Statistics.cpp.s

.PHONY : src/Statistics.s

# target to generate assembly for a file
src/Statistics.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/Statistics.cpp.s
	$(MAKE) -f CMakeFiles/STAT.dir/build.make CMakeFiles/STAT.dir/src/Statistics.cpp.s
.PHONY : src/Statistics.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz.dir/build.make CMakeFiles/ComplexQuiz.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/test0.o: test/test0.cpp.o

.PHONY : test/test0.o

# target to build an object file
test/test0.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test0.cpp.o
.PHONY : test/test0.cpp.o

test/test0.i: test/test0.cpp.i

.PHONY : test/test0.i

# target to preprocess a source file
test/test0.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test0.cpp.i
.PHONY : test/test0.cpp.i

test/test0.s: test/test0.cpp.s

.PHONY : test/test0.s

# target to generate assembly for a file
test/test0.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test0.cpp.s
.PHONY : test/test0.cpp.s

test/test1.o: test/test1.cpp.o

.PHONY : test/test1.o

# target to build an object file
test/test1.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test1.cpp.o
.PHONY : test/test1.cpp.o

test/test1.i: test/test1.cpp.i

.PHONY : test/test1.i

# target to preprocess a source file
test/test1.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test1.cpp.i
.PHONY : test/test1.cpp.i

test/test1.s: test/test1.cpp.s

.PHONY : test/test1.s

# target to generate assembly for a file
test/test1.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test1.cpp.s
.PHONY : test/test1.cpp.s

test/test2.o: test/test2.cpp.o

.PHONY : test/test2.o

# target to build an object file
test/test2.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test2.cpp.o
.PHONY : test/test2.cpp.o

test/test2.i: test/test2.cpp.i

.PHONY : test/test2.i

# target to preprocess a source file
test/test2.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test2.cpp.i
.PHONY : test/test2.cpp.i

test/test2.s: test/test2.cpp.s

.PHONY : test/test2.s

# target to generate assembly for a file
test/test2.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test2.cpp.s
.PHONY : test/test2.cpp.s

test/test3.o: test/test3.cpp.o

.PHONY : test/test3.o

# target to build an object file
test/test3.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test3.cpp.o
.PHONY : test/test3.cpp.o

test/test3.i: test/test3.cpp.i

.PHONY : test/test3.i

# target to preprocess a source file
test/test3.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test3.cpp.i
.PHONY : test/test3.cpp.i

test/test3.s: test/test3.cpp.s

.PHONY : test/test3.s

# target to generate assembly for a file
test/test3.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test3.cpp.s
.PHONY : test/test3.cpp.s

test/test4.o: test/test4.cpp.o

.PHONY : test/test4.o

# target to build an object file
test/test4.cpp.o:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test4.cpp.o
.PHONY : test/test4.cpp.o

test/test4.i: test/test4.cpp.i

.PHONY : test/test4.i

# target to preprocess a source file
test/test4.cpp.i:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test4.cpp.i
.PHONY : test/test4.cpp.i

test/test4.s: test/test4.cpp.s

.PHONY : test/test4.s

# target to generate assembly for a file
test/test4.cpp.s:
	$(MAKE) -f CMakeFiles/ComplexQuiz-ut.dir/build.make CMakeFiles/ComplexQuiz-ut.dir/test/test4.cpp.s
.PHONY : test/test4.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ComplexQuiz-ut"
	@echo "... ComplexQuiz"
	@echo "... STAT"
	@echo "... doctest"
	@echo "... QUIZ"
	@echo "... rebuild_cache"
	@echo "... EXPR"
	@echo "... COMP"
	@echo "... src/Complex.o"
	@echo "... src/Complex.i"
	@echo "... src/Complex.s"
	@echo "... src/Expression.o"
	@echo "... src/Expression.i"
	@echo "... src/Expression.s"
	@echo "... src/Quiz.o"
	@echo "... src/Quiz.i"
	@echo "... src/Quiz.s"
	@echo "... src/Statistics.o"
	@echo "... src/Statistics.i"
	@echo "... src/Statistics.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/test0.o"
	@echo "... test/test0.i"
	@echo "... test/test0.s"
	@echo "... test/test1.o"
	@echo "... test/test1.i"
	@echo "... test/test1.s"
	@echo "... test/test2.o"
	@echo "... test/test2.i"
	@echo "... test/test2.s"
	@echo "... test/test3.o"
	@echo "... test/test3.i"
	@echo "... test/test3.s"
	@echo "... test/test4.o"
	@echo "... test/test4.i"
	@echo "... test/test4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

